'use client'

import Link from 'next/link'
import { useState } from 'react'
import { ArrowRight, CalendarCheck, Check, CheckCircle, ChevronDown, Clock3, Command, Layers3, LockKeyhole, Mail, ShieldCheck, Sparkles, TrendingUp, UsersRound, X } from 'lucide-react'

const faqs = [
  ['Do my leads need an account?', 'No. Leads open your branded link, answer your questions, and get the next step. There is no LeadVett account or download required.'],
  ['Can I keep using my existing calendar?', 'Yes. LeadVett sits before your calendar. Qualified leads can be sent to the booking link you already use.'],
  ['What does LeadVett use to make a recommendation?', 'You set the non-negotiables—such as budget, location, service and timeline. LeadVett then assesses the context in each response and recommends the appropriate next action.'],
  ['Is this a CRM?', 'No. LeadVett is the qualification layer before your CRM and calendar. It helps you decide what happens next, then routes the lead into the tools your team already uses.'],
]

const outcomes = [
  { label: 'Ready to book', detail: 'Budget, timing and authority align', tone: 'bg-emerald-50 text-emerald-800 ring-emerald-200', icon: CalendarCheck },
  { label: 'Nurture', detail: 'Good fit, not ready to move yet', tone: 'bg-amber-50 text-amber-800 ring-amber-200', icon: Clock3 },
  { label: 'Not a fit', detail: 'A respectful no, without a call', tone: 'bg-slate-100 text-slate-700 ring-slate-200', icon: X },
]

export default function LeadVettLanding() {
  const [openFaq, setOpenFaq] = useState<number | null>(null)
  const [menuOpen, setMenuOpen] = useState(false)
  return <main className="min-h-screen overflow-x-hidden bg-[#f7f7f4] font-[family-name:var(--font-inter-tight)] text-[#111827]">
    <div className="pointer-events-none absolute inset-x-0 top-0 -z-0 h-[680px] bg-[radial-gradient(circle_at_50%_-10%,#dcecff_0%,#f7f7f4_58%)]" />
    <header className="relative z-20 mx-auto flex h-20 max-w-7xl items-center justify-between px-5 sm:px-8">
      <Link href="/" aria-label="LeadVett home" className="flex items-center gap-2 text-xl font-extrabold tracking-[-0.06em] text-slate-950"><span className="grid h-7 w-7 place-items-center rounded-lg bg-[#0d2545] text-sm text-white">L</span>Lead<span className="text-[#2878d4]">Vett</span></Link>
      <nav className="hidden items-center gap-8 text-sm font-medium text-slate-600 md:flex" aria-label="Main navigation"><Link className="transition hover:text-slate-950" href="#how-it-works">How it works</Link><Link className="transition hover:text-slate-950" href="#why-leadvett">Why LeadVett</Link><Link className="transition hover:text-slate-950" href="#pricing">Pricing</Link></nav>
      <div className="hidden items-center gap-5 md:flex"><Link href="/login" className="text-sm font-semibold text-slate-700 transition hover:text-slate-950">Sign in</Link><Link href="/signup" className="rounded-full bg-[#0d2545] px-5 py-3 text-sm font-semibold text-white shadow-[0_10px_24px_rgba(13,37,69,.18)] transition hover:-translate-y-0.5 hover:bg-[#173c69]">Start free</Link></div>
      <button aria-label="Toggle navigation" aria-expanded={menuOpen} onClick={() => setMenuOpen(!menuOpen)} className="grid h-11 w-11 place-items-center rounded-full border border-slate-200 bg-white text-slate-900 md:hidden"><Command size={19} aria-hidden="true" /></button>
    </header>
    {menuOpen && <div className="relative z-20 mx-5 rounded-2xl border border-slate-200 bg-white p-5 shadow-xl md:hidden"><nav className="flex flex-col gap-4 text-sm font-semibold text-slate-700" aria-label="Mobile navigation"><Link onClick={() => setMenuOpen(false)} href="#how-it-works">How it works</Link><Link onClick={() => setMenuOpen(false)} href="#why-leadvett">Why LeadVett</Link><Link onClick={() => setMenuOpen(false)} href="#pricing">Pricing</Link><Link onClick={() => setMenuOpen(false)} href="/signup" className="rounded-xl bg-[#0d2545] px-4 py-3 text-center text-white">Start free</Link></nav></div>}

    <section className="relative z-10 mx-auto grid max-w-7xl items-center gap-14 px-5 pb-24 pt-16 sm:px-8 lg:grid-cols-[1.02fr_.98fr] lg:pb-32 lg:pt-24"><div className="max-w-2xl"><div className="mb-7 inline-flex items-center gap-2 rounded-full border border-[#b9d6f7] bg-white/70 px-3 py-1.5 text-xs font-bold tracking-wide text-[#175ea9] shadow-sm"><span className="h-1.5 w-1.5 rounded-full bg-[#2878d4]" />QUALIFICATION BEFORE THE CALENDAR</div><h1 className="font-[family-name:var(--font-outfit)] text-5xl font-extrabold leading-[.98] tracking-[-0.065em] text-[#0d2545] sm:text-6xl lg:text-7xl">Protect your calendar for the work that matters.</h1><p className="mt-7 max-w-xl text-lg leading-8 text-slate-600 sm:text-xl">LeadVett turns every inbound enquiry into a clear next action—book, nurture, or decline—before it takes a minute from your team.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href="/signup" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-full bg-[#0d2545] px-6 text-sm font-bold text-white shadow-[0_14px_28px_rgba(13,37,69,.22)] transition hover:-translate-y-0.5 hover:bg-[#173c69]">Start qualifying leads <ArrowRight size={17} aria-hidden="true" /></Link><Link href="#how-it-works" className="inline-flex min-h-12 items-center justify-center rounded-full border border-slate-300 bg-white/80 px-6 text-sm font-bold text-[#0d2545] transition hover:border-[#2878d4] hover:text-[#175ea9]">See the workflow</Link></div><div className="mt-7 flex flex-wrap gap-x-6 gap-y-3 text-sm text-slate-600">{['3-day free trial', 'No card required', 'Set up in minutes'].map(item => <span key={item} className="flex items-center gap-2"><CheckCircle className="text-[#2878d4]" size={16} aria-hidden="true" />{item}</span>)}</div></div>
      <div className="relative mx-auto w-full max-w-xl lg:mx-0"><div className="absolute -inset-5 -z-10 rounded-[2rem] bg-[#8cc4ff]/25 blur-3xl" /><div className="overflow-hidden rounded-[1.6rem] border border-slate-200 bg-white shadow-[0_30px_70px_rgba(15,42,72,.18)]"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#e7f1fe] text-[#2878d4]"><Layers3 size={18} aria-hidden="true" /></span><div><p className="text-sm font-bold text-slate-900">New lead review</p><p className="text-xs text-slate-500">Website enquiry · just now</p></div></div><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-700 ring-1 ring-inset ring-emerald-200">High fit</span></div><div className="space-y-5 p-5 sm:p-7"><div className="rounded-2xl bg-[#f6f9fd] p-4"><p className="text-xs font-bold uppercase tracking-[.16em] text-slate-500">Lead signal summary</p><p className="mt-2 text-sm leading-6 text-slate-700">Clear project scope, confirmed budget and an active decision-maker. Timeline is inside 30 days.</p></div><div className="grid gap-3 sm:grid-cols-3">{[['Budget','$5k–$10k'],['Timeline','2–4 weeks'],['Authority','Decision maker']].map(([label,value]) => <div key={label} className="rounded-xl border border-slate-200 p-3"><p className="text-[11px] font-bold uppercase tracking-wider text-slate-400">{label}</p><p className="mt-1 text-sm font-bold text-slate-800">{value}</p></div>)}</div><div className="flex items-start gap-3 rounded-2xl border border-[#b9d6f7] bg-[#f1f7fe] p-4"><CalendarCheck className="mt-0.5 shrink-0 text-[#2878d4]" size={20} aria-hidden="true" /><div><p className="text-sm font-bold text-[#0d2545]">Recommended next step</p><p className="mt-1 text-sm text-slate-600">Invite them to book a 30-minute discovery call.</p></div></div><div className="flex items-center justify-between border-t border-slate-100 pt-4"><span className="text-xs font-medium text-slate-500">Reviewed in seconds, not another meeting.</span><span className="rounded-lg bg-[#0d2545] px-3 py-2 text-xs font-bold text-white">Approve route</span></div></div></div><div className="absolute -bottom-6 -left-5 hidden rounded-2xl border border-slate-200 bg-white p-4 shadow-xl sm:block"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-full bg-emerald-50 text-emerald-600"><TrendingUp size={18} aria-hidden="true" /></span><div><p className="text-xs font-bold text-slate-900">Calendar protected</p><p className="text-xs text-slate-500">One less unqualified call</p></div></div></div></div></section>

    <section className="relative z-10 border-y border-[#203c5b] bg-[#0d2545] px-5 py-7 sm:px-8"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-5 text-center sm:flex-row sm:text-left"><p className="font-[family-name:var(--font-outfit)] text-xl font-semibold tracking-tight text-white">A decision layer for every lead source.</p><div className="flex flex-wrap justify-center gap-x-7 gap-y-2 text-sm font-medium text-[#adc9e8]"><span>Website</span><span>Instagram</span><span>ManyChat</span><span>Referral</span><span>WhatsApp</span></div></div></section>
    <section id="how-it-works" className="mx-auto max-w-7xl px-5 py-24 sm:px-8 lg:py-32"><div className="grid gap-12 lg:grid-cols-[.7fr_1.3fr] lg:gap-24"><div><p className="text-xs font-extrabold tracking-[.18em] text-[#2878d4]">ONE CALM WORKFLOW</p><h2 className="mt-4 font-[family-name:var(--font-outfit)] text-4xl font-extrabold leading-tight tracking-[-.055em] text-[#0d2545] sm:text-5xl">Make every enquiry earn its place.</h2><p className="mt-5 max-w-sm text-base leading-7 text-slate-600">You define the standard. LeadVett gives every prospect a clear path and your team a confident next move.</p></div><div className="grid gap-4 md:grid-cols-3">{[['01','Capture the signal','Share one focused qualification link wherever leads find you.',UsersRound],['02','Apply your standard','Use your rules for budget, fit and timing; let AI read the context.',Sparkles],['03','Route the right action','Send the right people to a booking link, nurture path, or graceful no.',ArrowRight]].map(([number,title,copy,Icon]) => { const CardIcon = Icon as typeof UsersRound; return <article key={number as string} className="group rounded-2xl border border-slate-200 bg-white p-6 transition duration-200 hover:-translate-y-1 hover:border-[#b9d6f7] hover:shadow-lg"><span className="text-xs font-extrabold tracking-widest text-[#2878d4]">{number as string}</span><CardIcon className="mt-9 text-[#0d2545]" size={25} strokeWidth={1.7} aria-hidden="true"/><h3 className="mt-5 font-[family-name:var(--font-outfit)] text-xl font-bold tracking-tight text-slate-900">{title as string}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{copy as string}</p></article>})}</div></div></section>
    <section id="why-leadvett" className="bg-white px-5 py-24 sm:px-8 lg:py-32"><div className="mx-auto max-w-7xl"><div className="max-w-2xl"><p className="text-xs font-extrabold tracking-[.18em] text-[#2878d4]">A VERDICT IS ONLY USEFUL IF IT MOVES WORK FORWARD</p><h2 className="mt-4 font-[family-name:var(--font-outfit)] text-4xl font-extrabold leading-tight tracking-[-.055em] text-[#0d2545] sm:text-5xl">The answer is never just a score.</h2></div><div className="mt-14 grid gap-6 lg:grid-cols-[1.18fr_.82fr]"><div className="rounded-3xl bg-[#0d2545] p-7 text-white sm:p-10"><div className="flex items-center justify-between border-b border-white/15 pb-6"><div><p className="text-xs font-bold tracking-[.16em] text-[#9cc7f7]">LEAD POLICY</p><p className="mt-2 font-[family-name:var(--font-outfit)] text-2xl font-bold">Your standards, consistently applied.</p></div><ShieldCheck className="text-[#8cc4ff]" size={29} aria-hidden="true"/></div><div className="mt-7 grid gap-4 sm:grid-cols-2">{['Minimum budget requirement','Service and location fit','Decision authority','Project timing'].map(item => <div key={item} className="flex items-center gap-3 rounded-xl bg-white/8 px-4 py-3 text-sm font-semibold text-[#e3effe]"><Check size={16} className="text-[#8cc4ff]" aria-hidden="true" />{item}</div>)}</div><p className="mt-8 max-w-xl text-sm leading-6 text-[#b9d6f7]">Use hard rules for the dealbreakers. Give AI the context where it helps: clarity of need, urgency and quality of the response.</p></div><div className="grid gap-3">{outcomes.map(({label,detail,tone,icon: Icon}) => <div key={label} className="flex items-center gap-4 rounded-2xl border border-slate-200 bg-[#fafbfc] p-5"><span className={`grid h-11 w-11 place-items-center rounded-xl ring-1 ring-inset ${tone}`}><Icon size={20} aria-hidden="true" /></span><div><p className="font-bold text-slate-900">{label}</p><p className="mt-0.5 text-sm text-slate-600">{detail}</p></div></div>)}</div></div></div></section>
    <section id="pricing" className="px-5 py-24 sm:px-8 lg:py-32"><div className="mx-auto max-w-4xl rounded-[2rem] border border-[#b9d6f7] bg-[#eaf4ff] p-7 text-center sm:p-12"><p className="text-xs font-extrabold tracking-[.18em] text-[#2878d4]">SIMPLE PRICING</p><h2 className="mt-4 font-[family-name:var(--font-outfit)] text-4xl font-extrabold tracking-[-.055em] text-[#0d2545] sm:text-5xl">One plan. A clearer pipeline.</h2><p className="mx-auto mt-4 max-w-lg text-slate-600">Everything you need to qualify inbound leads before they take over your calendar.</p><div className="mx-auto mt-9 max-w-md rounded-2xl bg-white p-7 text-left shadow-[0_16px_40px_rgba(36,95,154,.13)]"><div className="flex items-end justify-between"><div><p className="text-sm font-bold text-slate-900">LeadVett Pro</p><p className="mt-1 text-sm text-slate-500">After your 3-day free trial</p></div><p className="font-[family-name:var(--font-outfit)] text-4xl font-extrabold tracking-tight text-[#0d2545]">$49<span className="text-base font-medium text-slate-500">/mo</span></p></div><ul className="mt-7 space-y-3 border-t border-slate-100 pt-6 text-sm text-slate-700">{['Custom qualification forms','Rules and AI signal analysis','Book, nurture and decline routes','Lead pipeline dashboard','Email support'].map(item => <li key={item} className="flex gap-3"><Check size={18} className="shrink-0 text-[#2878d4]" aria-hidden="true" />{item}</li>)}</ul><Link href="/signup" className="mt-8 flex min-h-12 items-center justify-center gap-2 rounded-xl bg-[#0d2545] px-5 text-sm font-bold text-white transition hover:bg-[#173c69]">Start free for 3 days <ArrowRight size={16} aria-hidden="true" /></Link></div></div></section>
    <section className="bg-white px-5 py-24 sm:px-8"><div className="mx-auto grid max-w-5xl gap-12 lg:grid-cols-[.75fr_1.25fr]"><div><p className="text-xs font-extrabold tracking-[.18em] text-[#2878d4]">FAQ</p><h2 className="mt-4 font-[family-name:var(--font-outfit)] text-4xl font-extrabold tracking-[-.055em] text-[#0d2545]">Questions, answered.</h2><p className="mt-4 text-slate-600">Built to make your first qualification workflow feel straightforward.</p></div><div className="divide-y divide-slate-200 border-y border-slate-200">{faqs.map(([question,answer],index) => <div key={question}><button onClick={() => setOpenFaq(openFaq === index ? null : index)} aria-expanded={openFaq === index} className="flex min-h-16 w-full items-center justify-between gap-5 py-4 text-left text-base font-bold text-slate-900"><span>{question}</span><ChevronDown className={`shrink-0 text-[#2878d4] transition ${openFaq === index ? 'rotate-180' : ''}`} size={20} aria-hidden="true" /></button>{openFaq === index && <p className="max-w-2xl pb-5 text-sm leading-7 text-slate-600">{answer}</p>}</div>)}</div></div></section>
    <section className="bg-[#0d2545] px-5 py-24 text-center sm:px-8 lg:py-32"><div className="mx-auto max-w-2xl"><LockKeyhole className="mx-auto text-[#8cc4ff]" size={25} aria-hidden="true"/><h2 className="mt-6 font-[family-name:var(--font-outfit)] text-4xl font-extrabold leading-tight tracking-[-.055em] text-white sm:text-6xl">Your calendar is a high-value asset.</h2><p className="mx-auto mt-5 max-w-lg text-lg leading-8 text-[#b9d6f7]">Give every lead a clear path—before your team gives them its time.</p><Link href="/signup" className="mt-9 inline-flex min-h-12 items-center gap-2 rounded-full bg-white px-6 text-sm font-bold text-[#0d2545] transition hover:-translate-y-0.5 hover:bg-[#eaf4ff]">Start qualifying leads <ArrowRight size={17} aria-hidden="true" /></Link><p className="mt-4 text-xs text-[#9cc7f7]">3-day free trial · No credit card required</p></div></section>
    <footer className="bg-[#08192f] px-5 py-9 sm:px-8"><div className="mx-auto flex max-w-7xl flex-col items-center justify-between gap-5 text-center sm:flex-row sm:text-left"><Link href="/" className="text-lg font-extrabold tracking-[-.06em] text-white">Lead<span className="text-[#8cc4ff]">Vett</span></Link><div className="flex gap-5 text-xs font-medium text-[#9cc7f7]"><Link className="hover:text-white" href="/privacy">Privacy</Link><Link className="hover:text-white" href="/terms">Terms</Link><Link className="hover:text-white" href="/contact">Contact</Link><a className="hover:text-white" href="mailto:contact@leadvett.com"><Mail className="inline-block align-text-bottom" size={13} aria-hidden="true" /> Support</a></div><p className="text-xs text-[#7191b6]">© {new Date().getFullYear()} LeadVett</p></div></footer>
  </main>
}
